#!/bin/env bash
import unittest
from models.base_model import BaseModel


class TestBaseModel(unittest.TestCase):

    def setUp(self):
        self.my_model = BaseModel()

    def test_name(self):
        self.my_model.name = "My First Model"
        self.assertEqual(self.my_model.name, "My First Model")

    def test_my_number(self):
        self.my_model.my_number = 89
        self.assertEqual(self.my_model.my_number, 89)

    def test_save(self):
        self.my_model.name = "My First Model"
        self.my_model.my_number = 89
        self.my_model.save()
        self.assertIsNotNone(self.my_model.id)
        self.assertIsNotNone(self.my_model.created_at)
        self.assertIsNotNone(self.my_model.updated_at)

    def test_to_dict(self):
        self.my_model.name = "My First Model"
        self.my_model.my_number = 89
        my_model_dict = self.my_model.to_dict()
        self.assertEqual(my_model_dict['name'], "My First Model")
        self.assertEqual(my_model_dict['my_number'], 89)
        self.assertIn('id', my_model_dict)
        self.assertIn('created_at', my_model_dict)
        self.assertIn('updated_at', my_model_dict)


if __name__ == '__main__':
    unittest.main()
